# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.1.0"

Vagrant.configure(2) do |config|

  config.vm.hostname = "books-mongodb"
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.synced_folder "../", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
    sudo apt-get update
    sudo apt-get install -y mongodb-org
    sudo sed -i "s/127.0.0.1/0.0.0.0/" /etc/mongod.conf
    sudo service mongod restart
    export LC_ALL=C
   SHELL

end
